<a href="https://colab.research.google.com/github/bggokmou/BigdataHomework/blob/master/5%EC%A3%BC%EC%B0%A8_%EA%B3%BC%EC%A0%9C3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# numpy 활용하기 : reshape() method

import numpy as np

temp = np.arange(48)
로 만든 1 차원 배열 temp 를

1. reshape method
활용하여 세번째 과제 에서 만든 임의의 3 차원 배열 (4, 3, 4), 2 차원
배열 (6,8) 을 만들어 보세요

2. github에 풀이 과정을 올리세요 학습사이트 과제제출에는 github url 만
올리세요.

In [8]:
import numpy as np

temp = np.arange(48)
np.random.shuffle(temp)
reshaped_temp = temp.reshape(4, 3, 4)

print(reshaped_temp)

[[[33  0 19 40]
  [25 30  4 12]
  [37 46 44 28]]

 [[ 3 15 18 36]
  [23  6 42 41]
  [16  5 22 32]]

 [[11  9 10 34]
  [47 43 27 17]
  [14 29  2 24]]

 [[20 31 13 35]
  [ 7 38 45 39]
  [26  1 21  8]]]


In [9]:
import numpy as np

temp = np.arange(48)
np.random.shuffle(temp)
reshaped_temp = temp.reshape(6, 8)

print(reshaped_temp)

[[25  3 30 27 20 31 15  9]
 [34  5 21 24  4 37 11 16]
 [18 40 17  7 10 28  0 46]
 [22 41 32  8 14 36 42 47]
 [43 23 44 29 35 13  1 45]
 [38  6 19 12 26  2 33 39]]
