<a href="https://colab.research.google.com/github/bggokmou/BigdataHomework/blob/master/5%EC%A3%BC%EC%B0%A8_%EA%B3%BC%EC%A0%9C1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

numpy 활용하기 : lotto 프로그램

1.앞의 lotto 프로그램의 결과를 3 회 실시하면서 매 회 결과를 list 에 담고 , 3 회에 결과를 모두 2 차원 배열의 shape 가 (3, 6) 되도록 만드세요
2. github
에 과제 ‘ 에 풀이 과정을 올리세요 학습사이트 과제제출에는 github url 만 올리세요

In [6]:
import numpy as np

a = np.arange(1, 46)
result = []

for i in range(3):
    np.random.shuffle(a)
    lotto = a[:6]
    print(f"{i+1}회차 로또 추첨 결과 =", lotto)
    result.append(lotto)

result_array = np.array(result)
print(result_array)


1회차 로또 추첨 결과 = [35 32  5 16 43  7]
2회차 로또 추첨 결과 = [ 3  8 16 37 43 29]
3회차 로또 추첨 결과 = [35 37 34 23 26 15]
[[35 37 34 23 26 15]
 [35 37 34 23 26 15]
 [35 37 34 23 26 15]]
