<a href="https://colab.research.google.com/github/bggokmou/BigdataHomework/blob/master/5%EC%A3%BC%EC%B0%A8_%EA%B3%BC%EC%A0%9C2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# numpy 활용하기 :3 차원배열 만들기

# 임의의 3 차열 배열 만들기 코드

import numpy as np

3차원 배열의 크기를 지정합니다

shape = (3, 4, 5)

3차원 배열을 생성합니다

arr = np.random.randint(0, 10, shape)

3차원 배열을 출력합니다

print(arr)

위의코드를 참조하여

1.shape 가 (3, 3, 6) 이고 , 배열 원소가 0~20 사이의 정수 값을 갖도록 임의의 3차원 배열을 만드세요.

2.shape 가 (5, 6) 이고 , 배열 원소가 0~100 사이의 정수 값을 갖도록 임의의 2차원 배열을 만드세요.

3.github에 과제 ‘ 에 풀이 과정을 올리세요 학습사이트 과제제출에는 github url 만 올리세요.


In [3]:
import numpy as np

shape = (3,3,6)
arr = np.random.randint(0,20,shape)
print(arr)

[[[ 7 14 18 17 11  1]
  [11 13  7  5  8  5]
  [17 16  9 16 14 14]]

 [[ 4  6 13  5  5  0]
  [15 12  3 10 18  6]
  [17  3  8 19 10  7]]

 [[ 0  6 19  7 14  0]
  [18 15 15 15  3  1]
  [ 3 11 18  7  8 10]]]


In [4]:
shape = (5,6)
arr = np.random.randint(0,100,shape)
print(arr)

[[77 39 74 68 77 24]
 [51 85 10 62 67 44]
 [60 58  2 79 98 19]
 [94  9 39 79 66 97]
 [80 23 95 23 66 33]]
